apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana-deploy
  template:
    metadata:
      labels:
        app: grafana-deploy
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
