apiVersion: v1
kind: Service
metadata:
  name: static-web-service
spec:
  selector:
    app: static-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # If using Minikube, use NodePort instead
